if(NOT DEFINED INPUT)
    message(FATAL_ERROR "INPUT must name the readable text asset source")
endif()

if(NOT DEFINED OUTPUT AND NOT DEFINED CHECK)
    message(FATAL_ERROR "Set OUTPUT to regenerate the header or CHECK to verify it")
endif()

if(NOT DEFINED STRUCT)
    message(FATAL_ERROR "STRUCT must name the generated struct, e.g. WebFrontJsData")
endif()

# Embed the source bytes directly. Compression libraries can produce different
# deflate streams on different platforms, while the raw representation is
# deterministic and is small enough for this development asset.
file(READ "${INPUT}" gzip_hex HEX)

string(LENGTH "${gzip_hex}" hex_length)
math(EXPR data_size "${hex_length} / 2")
math(EXPR word_count "(${data_size} + 7) / 8")

set(words "")
set(word_index 0)
while(word_index LESS word_count)
    math(EXPR offset "${word_index} * 16")
    math(EXPR remaining "${hex_length} - ${offset}")
    if(remaining GREATER 16)
        set(chunk_length 16)
    else()
        set(chunk_length "${remaining}")
    endif()
    string(SUBSTRING "${gzip_hex}" "${offset}" "${chunk_length}" word)
    string(LENGTH "${word}" word_length)
    while(word_length LESS 16)
        string(APPEND word "0")
        string(LENGTH "${word}" word_length)
    endwhile()
    math(EXPR line_position "${word_index} % 5")
    if(line_position EQUAL 0)
        if(word_index GREATER 0)
            string(APPEND words ",")
        endif()
        string(APPEND words "\n        ")
    elseif(word_index GREATER 0)
        string(APPEND words ", ")
    endif()
    string(APPEND words "0x${word}")
    math(EXPR word_index "${word_index} + 1")
endwhile()

set(contents "#pragma once\n\n#include <array>\n#include <cstddef>\n#include <cstdint>\n#include <string_view>\n\nnamespace webfront::fs::generated {\n\nstruct ${STRUCT} {\n    static constexpr std::string_view encoding{};\n    static constexpr std::size_t dataSize{${data_size}};\n    static constexpr std::array<std::uint64_t, ${word_count}> data{${words}\n    };\n};\n\n} // namespace webfront::fs::generated\n")

if(DEFINED CHECK)
    file(READ "${CHECK}" expected)
    if(NOT contents STREQUAL expected)
        message(FATAL_ERROR "${CHECK} is stale; run the webfront-embedded-assets target")
    endif()
else()
    file(WRITE "${OUTPUT}" "${contents}")
endif()
