name: Build and Test

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ master develop ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        compiler: [msvc, gcc, clang]
        exclude:
        - os: windows-latest
          compiler: gcc
        - os: windows-latest
          compiler: clang
        - os: ubuntu-latest
          compiler: msvc
        - os: macos-latest
          compiler: msvc
        - os: macos-latest
          compiler: gcc
    runs-on: ${{ matrix.os}}
      
    steps:
      - name: Setup Clang
        uses: egor-tensin/setup-clang@v1.4
        if: os.compiler == 'clang'
      - name: Setup GCC
        uses: egor-tensin/setup-gcc@v1
        if: os.compiler == 'gcc'

      
