name: Build and Test

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ master develop ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        compiler: [msvc, gcc, clang]
        exclude:
        - os: windows-latest
          compiler: clang
        - os: windows-latest
          compiler: gcc
        - os: ubuntu-latest
          compiler: msvc
        - os: macos-latest
          compiler: msvc
        - os: macos-latest
          compiler: gcc
        - os: ubuntu-latest
          compiler: clang
    runs-on: ${{ matrix.os}}
    name: ${{ matrix.os }}-${{ matrix.compiler }}
      
    steps:
      - uses: actions/checkout@v4
        
      - name: Setup Clang
        uses: egor-tensin/setup-clang@v1.4
        with:
          version: 15
        if: matrix.os == 'ubuntu-latest' && matrix.compiler == 'clang'

      - name: Setup GCC
        uses: egor-tensin/setup-gcc@v1.3
        with:
          version: 13
        if: matrix.compiler == 'gcc'
        
      - name: Config & Build
        run: |
          cmake . -B ${{github.workspace}}/build
          cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
  
      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest --verbose -C ${{env.BUILD_TYPE}}

      - name: Create Badge JSON
        if: always() && github.ref == 'refs/heads/master'
        id: create_json
        run: |
          echo "{\"schemaVersion\":1,\"label\":\"Build\",\"message\":\"pending\",\"color\":\"yellow\"}" > current_badge.json
          BADGE_NAME="${{ matrix.os }}-${{ matrix.compiler }}.json"
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            BADGE_LABEL="Windows MSVC"
          elif [[ "${{ matrix.os }}" == "ubuntu-latest" && "${{ matrix.compiler }}" == "gcc" ]]; then
            BADGE_LABEL="Ubuntu GCC"
          elif [[ "${{ matrix.os }}" == "ubuntu-latest" && "${{ matrix.compiler }}" == "clang" ]]; then
            BADGE_LABEL="Ubuntu Clang"
          else
            BADGE_LABEL="MacOS Clang"
          fi
          echo "::set-output name=badge_label::$BADGE_LABEL"
          echo "::set-output name=badge_name::$BADGE_NAME"
        shell: bash

      - name: Initialize Gist
        if: always() && github.ref == 'refs/heads/master'
        uses: gist-sync/actions/sync@v1.0.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gist_id: 317c22bfe80b2b51663187fbebfba533
          gist_file_name: ${{ steps.create_json.outputs.badge_name }}
          file: current_badge.json
          
      - name: Update Badge
        if: always() && github.ref == 'refs/heads/master'
        uses: schneegans/dynamic-badges-action@v1.6.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 317c22bfe80b2b51663187fbebfba533
          filename: ${{ steps.create_json.outputs.badge_name }}
          label: ${{ steps.create_json.outputs.badge_label }}
          message: ${{ job.status }}
          color: ${{ job.status == 'success' && '2EA043' || job.status == 'failure' && 'E6484F' || 'DBAB0A' }}

