name: Build and Test

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ master develop ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        compiler: [msvc, gcc, clang]
        exclude:
        - os: windows-latest
          compiler: clang
        - os: windows-latest
          compiler: gcc
        - os: ubuntu-latest
          compiler: msvc
        - os: macos-latest
          compiler: msvc
        - os: macos-latest
          compiler: gcc
        - os: ubuntu-latest
          compiler: clang
    runs-on: ${{ matrix.os}}
    name: ${{ matrix.os }}-${{ matrix.compiler }}
      
    steps:
      - uses: actions/checkout@v4
        
      - name: Setup Clang
        uses: egor-tensin/setup-clang@v1.4
        with:
          version: 15
        if: matrix.os == 'ubuntu-latest' && matrix.compiler == 'clang'

      - name: Setup GCC
        uses: egor-tensin/setup-gcc@v1.3
        with:
          version: 13
        if: matrix.compiler == 'gcc'
        
      - name: Config & Build
        run: |
          cmake . -B ${{github.workspace}}/build
          cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
  
      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest --verbose -C ${{env.BUILD_TYPE}}

      - name: Update Badge Data
        if: always() && github.ref == 'refs/heads/master'
        run: |
          # Determine badge label and color
          BADGE_LABEL=""
          case "${{ matrix.os }}-${{ matrix.compiler }}" in
            "windows-latest-msvc")
              BADGE_LABEL="Windows MSVC"
              ;;
            "ubuntu-latest-gcc")
              BADGE_LABEL="Ubuntu GCC"
              ;;
            "ubuntu-latest-clang")
              BADGE_LABEL="Ubuntu Clang"
              ;;
            *)
              BADGE_LABEL="MacOS Clang"
              ;;
          esac
          
          COLOR=""
          case "${{ job.status }}" in
            "success")
              COLOR="2EA043"
              ;;
            "failure")
              COLOR="E6484F"
              ;;
            *)
              COLOR="DBAB0A"
              ;;
          esac
          
          # Create badge JSON content
          JSON_CONTENT="{\"schemaVersion\":1,\"label\":\"$BADGE_LABEL\",\"message\":\"${{ job.status }}\",\"color\":\"$COLOR\"}"
          
          # Escape JSON for curl
          ESCAPED_JSON=$(echo "$JSON_CONTENT" | jq -c '.')
          
          # Update Gist using curl
          curl -L \
            -X PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GIST_SECRET }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -H "Content-Type: application/json" \
            https://api.github.com/gists/317c22bfe80b2b51663187fbebfba533 \
            -d "{\"files\":{\"`echo ${{ matrix.os }}-${{ matrix.compiler }}.json`\":{\"content\":$ESCAPED_JSON}}}"
        shell: bash

      - name: Update Badge
        if: always() && github.ref == 'refs/heads/master'
        uses: schneegans/dynamic-badges-action@v1.6.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 317c22bfe80b2b51663187fbebfba533
          filename: ${{ matrix.os }}-${{ matrix.compiler }}.json
          label: ${{ matrix.os == 'windows-latest' && 'Windows MSVC' || matrix.os == 'ubuntu-latest' && matrix.compiler == 'gcc' && 'Ubuntu GCC' || matrix.os == 'ubuntu-latest' && matrix.compiler == 'clang' && 'Ubuntu Clang' || matrix.os == 'macos-latest' && 'MacOS Clang' }}
          message: ${{ job.status }}
          color: ${{ job.status == 'success' && '2EA043' || job.status == 'failure' && 'E6484F' || 'DBAB0A' }}

